# Generated by Django 6.0 on 2026-01-08 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_order_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 11, 16, 27, 1, 721973, tzinfo=datetime.timezone.utc)),
        ),
    ]
