# Generated by Django 6.0.1 on 2026-01-22 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0009_order_delivery_address_order_delivery_instructions_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 25, 18, 16, 49, 897432, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
