# Generated by Django 6.0.1 on 2026-01-22 18:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_subscriber_alter_order_delivery_date_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available_for_order",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Active (Show on website)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_popular",
            field=models.BooleanField(
                default=False, verbose_name="Popular (Best Seller)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_special_offer",
            field=models.BooleanField(default=False, verbose_name="Special Offer"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 25, 18, 42, 25, 886345, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="SavedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
                "unique_together": {("user", "product")},
            },
        ),
    ]
