# Generated by Django 6.0.1 on 2026-01-22 19:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_product_available_for_order_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 25, 19, 10, 43, 640837, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="ShipmentTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nepal_post_tracking_number",
                    models.CharField(max_length=20, unique=True),
                ),
                (
                    "current_location",
                    models.CharField(default="Processing", max_length=200),
                ),
                (
                    "current_status",
                    models.CharField(default="Package Received", max_length=50),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("tracking_history", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nepal_post_tracking",
                        to="inventory.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nepal Post Tracking",
                "verbose_name_plural": "Nepal Post Trackings",
                "ordering": ["-created_at"],
            },
        ),
    ]
