# Generated by Django 6.0.1 on 2026-01-24 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_alter_order_delivery_date_shipmenttracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 27, 10, 4, 27, 232120, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
