# Generated by Django 6.0.1 on 2026-01-24 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_alter_order_delivery_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 27, 15, 24, 34, 204620, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
