# Generated by Django 6.0.1 on 2026-01-26 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_alter_order_delivery_date_alter_profile_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header_title", models.CharField(default="FurniQ", max_length=100)),
                (
                    "footer_text",
                    models.TextField(default="Premium Furniture for your home."),
                ),
                (
                    "footer_address",
                    models.CharField(default="Kathmandu, Nepal", max_length=255),
                ),
                (
                    "contact_email",
                    models.EmailField(default="info@furniq.com", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(default="+977 12345678", max_length=20),
                ),
                (
                    "featured_title",
                    models.CharField(default="Lush Collection 2026", max_length=200),
                ),
                (
                    "featured_subtitle",
                    models.CharField(
                        default="Discover the Art of Living", max_length=200
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="site_assets/"),
                ),
                ("about_title", models.CharField(default="Our Story", max_length=100)),
                (
                    "about_content",
                    models.TextField(
                        default="We craft furniture with love and precision."
                    ),
                ),
                (
                    "about_image",
                    models.ImageField(blank=True, null=True, upload_to="site_assets/"),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 29, 14, 27, 19, 452125, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
